---
version: 1.1.x.{build}
branches:
  only:
    - master
    - release
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
image: 'Visual Studio 2022'
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
install:
  - choco install pdk --version 3.4.0.1 -y
  - setx /M path "%path%;C:\Progra~1\Puppet~1\DevelopmentKit\bin\"
  - refreshenv
build: false
test_script:
  - C:\Progra~1\Puppet~1\DevelopmentKit\bin\pdk validate --puppet-version=8 'puppet,metadata,yaml'
  - C:\Progra~1\Puppet~1\DevelopmentKit\bin\pdk test unit --puppet-version=8
notifications:
  - provider: Email
    to:
      - puppet-modulebouw@kpn.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
